Repository Journey-Together/DaOnGil_CleanArchitecture, pull requests merged in 2024-11, with the labels that each got.

#295 [#294] 기본 이미지 리소스 변경
  DaOnGil/presentation/src/main/res/drawable-night/empty_view.xml
  DaOnGil/presentation/src/main/res/drawable-night/empty_view_long.xml
  DaOnGil/presentation/src/main/res/drawable-night/empty_view_small.xml
  DaOnGil/presentation/src/main/res/drawable/empty_view.xml
  DaOnGil/presentation/src/main/res/drawable/empty_view_long.xml
  DaOnGil/presentation/src/main/res/drawable/empty_view_small.xml
Labels: UI/UX, 리팩토링

#298 #296 관심유형 선택 후 화면 이동 불가시 재시도 버튼 추가
  DaOnGil/domain/src/main/java/kr/techit/lion/domain/model/ConcernType.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/delegate/NetworkErrorDelegate.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/login/fragment/LoginFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/login/fragment/SelectInterestFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/login/model/UserState.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/login/vm/InterestViewModel.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/login/vm/LoginViewModel.kt
  DaOnGil/presentation/src/main/res/layout/fragment_select_interest.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: 버그

#302 [#299] 카카오 버튼 가시성 숨기기
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/login/fragment/LoginFragment.kt
  DaOnGil/presentation/src/main/res/layout/fragment_login.xml
Labels: 버그

#301 [#300] 고대비 전환 임시 처리
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/main/dialog/ThemeTempDialog.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/res/drawable/image_theme_temp.png
  DaOnGil/presentation/src/main/res/layout/dialog_theme_temp.xml
Labels: 기능, 리팩토링

#305 [#304]사용자 테마 가져오기 flow로 수정
  DaOnGil/data/src/main/java/kr/techit/lion/data/datasource/AppThemeDataSource.kt
  DaOnGil/data/src/main/java/kr/techit/lion/data/repository/AppThemeRepositoryImpl.kt
  DaOnGil/domain/src/main/java/kr/techit/lion/domain/model/AppTheme.kt
  DaOnGil/domain/src/main/java/kr/techit/lion/domain/repository/AppThemeRepository.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/main/vm/home/HomeViewModel.kt
Labels: 리팩토링

#310 [#303] 사용자 이름 수정 기능 추가
  DaOnGil/data/src/main/java/kr/techit/lion/data/dto/request/MyPersonalInfoRequest.kt
  DaOnGil/domain/src/main/java/kr/techit/lion/domain/model/IceInfo.kt
  DaOnGil/domain/src/main/java/kr/techit/lion/domain/model/PersonalInfo.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/main/vm/myinfo/MyInfoMainViewModel.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/main/vm/myinfo/model/ProfileState.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/myinfo/fragment/IceModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/myinfo/fragment/MyInfoFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/myinfo/fragment/PersonalInfoModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/myinfo/intent/MyInfoIntent.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/myinfo/model/MyInfoState.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/myinfo/vm/MyInfoViewModel.kt
  DaOnGil/presentation/src/main/res/layout/fragment_personal_info_modify.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: 기능, 리팩토링

#309 [#297] 홈 화면 위치 에러
  DaOnGil/.idea/deploymentTargetSelector.xml
  DaOnGil/domain/src/main/java/kr/techit/lion/domain/model/AppTheme.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/main/vm/home/HomeViewModel.kt
Labels: 기능, 리팩토링

#312 [#311] 최초 로그인시 관심유형 api 호출시 프로그래스바 추가
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/login/OnBoardingActivity.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/login/fragment/LoginFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/login/model/InterestType.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/login/model/UserState.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/login/model/UserType.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/login/vm/LoginViewModel.kt
Labels: 리팩토링
