Repository Journey-Together/DaOnGil_CleanArchitecture, pull requests merged in 2024-09, with the labels that each got.

#52 [Feat] 로그인 및 관심유형 선택 화면 접근성 개발
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/delegate/NetworkErrorDelegate.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/fragment/OnBoardingFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/fragment/SelectInterestFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/model/FocusOn.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/model/InterestType.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/vm/InterestViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/vm/OnBoardingViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/myinfo/MyInfoMainViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/splash/OnBoardingActivity.kt
  DaOnGil/presentation/src/main/res/layout/activity_on_boarding.xml
  DaOnGil/presentation/src/main/res/layout/fragment_login.xml
  DaOnGil/presentation/src/main/res/layout/fragment_on_boarding.xml
  DaOnGil/presentation/src/main/res/layout/fragment_select_interest.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: 기능

#56 [#51] naver api 사용자 위치 연결
  DaOnGil/data/build.gradle.kts
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/NaverMapDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/di/NetworkModule.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/di/Qualifiers.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/di/RepositoryModule.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/naverMap/Area0.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/naverMap/Center.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/naverMap/Code.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/naverMap/Coords.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/naverMap/Region.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/naverMap/Result.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/naverMap/ReverseGeocodeResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/naverMap/Status.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/NaverMapRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/NaverMapService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/ReverseGeocodes.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/NaverMapRepository.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/emergency/EmergencyMapActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/emergency/vm/EmergencyMapViewModel.kt
Labels: 기능

#58 [#47] 여행 일정 메인 화면 기본 세팅
  DaOnGil/presentation/src/main/AndroidManifest.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/schedule/ScheduleMainViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/MyScheduleActivity.kt
  DaOnGil/presentation/src/main/res/layout/activity_my_schedule.xml
  DaOnGil/presentation/src/main/res/layout/fragment_schedule_main.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX, 기능

#61 [#59] 내 일정 목록 UI api 연결
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/PlanDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/di/NetworkModule.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/di/RepositoryModule.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/myScheduleElapsed/Data.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/myScheduleElapsed/MyElapsedResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/myScheduleElapsed/PlanRes.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/myScheduleUpcoming/Data.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/myScheduleUpcoming/MyUpcomingsResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/myScheduleUpcoming/PlanRes.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/PlanRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/PlanService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/schedule/MyElapsedScheduleInfo.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/schedule/MyElapsedSchedules.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/schedule/MyUpcomingScheduleInfo.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/schedule/MyUpcomingSchedules.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/PlanRepository.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/MyScheduleActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/adapter/MyScheduleElapsedAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/adapter/MyScheduleUpcomingAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/vm/MyScheduleViewModel.kt
  DaOnGil/presentation/src/main/res/layout/activity_my_schedule.xml
  DaOnGil/presentation/src/main/res/layout/item_my_schedule_elapsed.xml
  DaOnGil/presentation/src/main/res/layout/item_my_schedule_upcoming.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX, 기능

#64 [#62] 새로운 일정 만드는 화면 연결
  DaOnGil/.idea/navEditor.xml
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/scheduleform/DailySchedule.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/scheduleform/FormPlace.kt
  DaOnGil/presentation/src/main/AndroidManifest.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/DateFormatExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/SnackbarExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/ScheduleFormActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/FormSearchFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/NameAndPeriodFormFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/ScheduleConfirmFormFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/ScheduleDetailsFormFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/vm/ScheduleFormViewModel.kt
  DaOnGil/presentation/src/main/res/drawable/calendar_icon.xml
  DaOnGil/presentation/src/main/res/layout/activity_schedule_form.xml
  DaOnGil/presentation/src/main/res/layout/fragment_form_search.xml
  DaOnGil/presentation/src/main/res/layout/fragment_name_and_period_form.xml
  DaOnGil/presentation/src/main/res/layout/fragment_schedule_confirm_form.xml
  DaOnGil/presentation/src/main/res/layout/fragment_schedule_details_form.xml
  DaOnGil/presentation/src/main/res/navigation/schedule_form_graph.xml
  DaOnGil/presentation/src/main/res/values-night/colors.xml
  DaOnGil/presentation/src/main/res/values/colors.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX

#73 [#71] 여행 일정 메인화면 내 일정 기능 구현
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/PlanDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/myMainSchedule/Data.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/myMainSchedule/MyMainScheduleResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/PlanRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/PlanService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/MyMainSchedule.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/PlanRepository.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/ScheduleMyAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/schedule/ScheduleMainViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedule/ResultCode.kt
  DaOnGil/presentation/src/main/res/layout/row_schedule_my.xml
Labels: UI/UX, 기능

#75 [#74] 여행 일정 메인화면 공개 일정 기능 구현
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/PlanDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/openSchedule/Data.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/openSchedule/OpenPlanListResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/openSchedule/OpenPlanRes.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/PlanRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/PlanService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/OpenPlan.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/OpenPlanInfo.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/PlanRepository.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/SchedulePublicAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/schedule/ScheduleMainViewModel.kt
  DaOnGil/presentation/src/main/res/layout/row_schedule_public.xml
Labels: UI/UX, 기능

#78 [#65] 새로운 일정 화면 api 연결
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/PlanDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/request/DailyPlaceRequest.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/request/NewPlanRequest.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/scheduleform/PlaceSearchInfoData.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/scheduleform/PlaceSearchResultsData.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/scheduleform/PlaceSearchResultsResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/PlanRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/PlanService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/scheduleform/DailyPlace.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/scheduleform/NewPlan.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/scheduleform/PlaceSearchInfoList.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/scheduleform/PlaceSearchResult.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/PlanRepository.kt
  DaOnGil/gradle/libs.versions.toml
  DaOnGil/presentation/build.gradle.kts
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/DateFormatExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/FormDateFormat.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/adapter/FormBookmarkedPlacesAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/adapter/FormConfirmPlaceAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/adapter/FormConfirmScheduleAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/adapter/FormPlaceAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/adapter/FormScheduleAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/adapter/FormSearchResultAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/FormSearchFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/NameAndPeriodFormFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/ScheduleConfirmFormFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/ScheduleDetailsFormFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/vm/ScheduleFormViewModel.kt
  DaOnGil/presentation/src/main/res/drawable/dotted_line_border.xml
  DaOnGil/presentation/src/main/res/drawable/dotted_line_vertical.xml
  DaOnGil/presentation/src/main/res/drawable/form_add_icon.xml
  DaOnGil/presentation/src/main/res/drawable/form_remove_icon.xml
  DaOnGil/presentation/src/main/res/layout/item_form_bookmarked_places.xml
  DaOnGil/presentation/src/main/res/layout/item_form_confirm.xml
  DaOnGil/presentation/src/main/res/layout/item_form_place.xml
  DaOnGil/presentation/src/main/res/layout/item_form_schedule.xml
  DaOnGil/presentation/src/main/res/layout/item_form_search_result.xml
  DaOnGil/presentation/src/main/res/layout/item_form_search_total.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX, 기능

#77 [#48] 여행지 후기 목록 및 삭제, 수정 구현
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/PlaceDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/di/NetworkModule.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/request/MyPlaceReivewImgRequest.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/request/MyPlaceReviewRequest.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/request/util/LocalDateAdapter.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/myreview/MyPlaceReviewData.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/myreview/MyPlaceReviewDto.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/myreview/MyPlaceReviewResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/PlaceRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/PlaceService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/MyPlaceReview.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/MyPlaceReviewImages.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/MyPlaceReviewInfo.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/UpdateMyPlaceReview.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/PlaceRepository.kt
  DaOnGil/gradle/libs.versions.toml
  DaOnGil/presentation/build.gradle.kts
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/ContextExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/MyReviewActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/PhotoDialog.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/adapter/MyReviewImageRVAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/adapter/MyReviewModifyImageRVAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/adapter/MyReviewRVAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/adapter/PhotoVPAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/fragment/MyReviewFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/fragment/MyReviewModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/vm/MyReviewViewModel.kt
  DaOnGil/presentation/src/main/res/drawable-night/review_image_icon.xml
  DaOnGil/presentation/src/main/res/drawable/close_icon.xml
  DaOnGil/presentation/src/main/res/drawable/dotted_line_horizontal.xml
  DaOnGil/presentation/src/main/res/drawable/review_image_icon.xml
  DaOnGil/presentation/src/main/res/layout/dialog_photo.xml
  DaOnGil/presentation/src/main/res/layout/fragment_my_review.xml
  DaOnGil/presentation/src/main/res/layout/fragment_my_review_modify.xml
  DaOnGil/presentation/src/main/res/layout/item_my_review.xml
  DaOnGil/presentation/src/main/res/layout/item_my_review_header.xml
  DaOnGil/presentation/src/main/res/layout/item_photo_vp.xml
  DaOnGil/presentation/src/main/res/layout/item_review_write_image.xml
  DaOnGil/presentation/src/main/res/navigation/nav_my_review_graph.xml
  DaOnGil/presentation/src/main/res/values-night/colors.xml
  DaOnGil/presentation/src/main/res/values/colors.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX, 기능

#81 [#80] color resources 중복 오류
  DaOnGil/presentation/src/main/res/values-night/colors.xml
  DaOnGil/presentation/src/main/res/values/colors.xml
Labels: 버그

#83 [#82] merge하면서 생긴 오류 해결
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/PlaceDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/PlaceService.kt
Labels: 버그

#85 [#72] 관광지 리뷰 작성 구현
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/PlaceDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/di/NetworkModule.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/request/NewReviewDataRequest.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/request/PlaceReviewImageRequest.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/request/adapter/LocalDateAdapter.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/placereview/WritePlaceReviewResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/PlaceRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/PlaceService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/placereview/NewReviewData.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/placereview/NewReviewImages.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/placereview/WritePlaceReview.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/PlaceRepository.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/DetailActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/WriteReviewActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/adapter/WriteReviewImageRVAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/model/NewReviewImgs.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/vm/WriteReviewViewModel.kt
  DaOnGil/presentation/src/main/res/layout/activity_write_review.xml
  DaOnGil/presentation/src/main/res/layout/fragment_home_main.xml
  DaOnGil/presentation/src/main/res/values-night/colors.xml
  DaOnGil/presentation/src/main/res/values/colors.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX, 기능

#84 [#79] 여행일정 여행지 상세정보 api 연결
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/myScheduleElapsed/Data.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/myScheduleElapsed/MyElapsedResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/myScheduleElapsed/PlanRes.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/myScheduleUpcoming/Data.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/myScheduleUpcoming/MyUpcomingsResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/myScheduleUpcoming/PlanRes.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/FormSearchFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/ScheduleConfirmFormFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/ScheduleDetailsFormFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/vm/ScheduleFormViewModel.kt
Labels: 기능

#88 [#86] 관광지 상세보기 리뷰 데이터 구조 수정
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/detailplace/DetailPlaceResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/detailplace/ReviewRes.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/detailplaceguest/DetailPlaceGuestResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/detailplaceguest/ReviewGuestRes.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/detailplace/Review.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/adapter/DetailReviewRVAdapter.kt
  DaOnGil/presentation/src/main/res/layout/item_detail_review_big.xml
Labels: UI/UX, 리팩토링

#90 [#89] 관광지 후기 전체보기 구현
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/PlaceDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/placereviewlist/Data.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/placereviewlist/MyPlaceReview.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/placereviewlist/PlaceReviewResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/PlaceRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/PlaceService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/placereviewlist/PlaceReview.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/placereviewlist/PlaceReviewInfo.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/PlaceRepository.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/ReviewListActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/adapter/ReviewListRVAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/vm/ReviewListViewModel.kt
  DaOnGil/presentation/src/main/res/layout/activity_review_list.xml
Labels: UI/UX, 기능

#99 [55] 키워드 검색 구현 완료
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/request/ConcernTypeRequest.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/request/MyIceInfoRequest.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/request/MyPersonalInfoRequest.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/request/util/AdapterProvider.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/searchplace/AutoCompleteKeywordResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/searchplace/auto_complete_keyword/AutoCompleteKeywordResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/searchplace/auto_complete_keyword/Data.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/MemberRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/PlaceRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/RecentlySearchKeywordRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/PlaceService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/search/AutoCompleteKeyword.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/PlaceRepository.kt
  DaOnGil/presentation/src/main/AndroidManifest.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/delegate/NetworkErrorDelegate.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/ContextExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/KeywordSearchActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/adapter/SearchResultAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/adapter/SearchSuggestionsAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/fragment/OnSearchFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/fragment/SearchResultFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/model/KeywordInputState.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/viewholder/RecentlyKeywordViewHolder.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/viewholder/SearchSuggestionsViewHolder.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/vm/KeywordSearchViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/vm/SearchResultViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/ListSearchAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/RecentlyKeywordAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/viewholder/PlaceHighViewHolder.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/SearchListFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/SearchPlaceMainFragment.kt
  DaOnGil/presentation/src/main/res/anim/for_slide_in_right.xml
  DaOnGil/presentation/src/main/res/anim/for_slide_out_left.xml
  DaOnGil/presentation/src/main/res/drawable-night/progress_icon.xml
  DaOnGil/presentation/src/main/res/drawable/elderly_people_radius_icon.xml
  DaOnGil/presentation/src/main/res/drawable/hearing_impairment_radius_icon.xml
  DaOnGil/presentation/src/main/res/drawable/ic_close.xml
  DaOnGil/presentation/src/main/res/drawable/infant_familly_radius_icon.xml
  DaOnGil/presentation/src/main/res/drawable/physical_disability_radius_icon.xml
  DaOnGil/presentation/src/main/res/drawable/progress_icon.xml
  DaOnGil/presentation/src/main/res/drawable/rotate_progress_bar.xml
  DaOnGil/presentation/src/main/res/drawable/visual_impairment_radius_icon.xml
  DaOnGil/presentation/src/main/res/layout/activity_keyword_search.xml
  DaOnGil/presentation/src/main/res/layout/fragment_on_search.xml
  DaOnGil/presentation/src/main/res/layout/fragment_search_place_main.xml
  DaOnGil/presentation/src/main/res/layout/fragment_search_result.xml
  DaOnGil/presentation/src/main/res/layout/item_recently_search_keyword.xml
  DaOnGil/presentation/src/main/res/navigation/nav_keyword_search_graph.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX, 기능

#96 [#92] 신고하기 화면 구현
  DaOnGil/.idea/other.xml
  DaOnGil/presentation/src/main/AndroidManifest.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/report/ReportActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/report/vm/ReportViewModel.kt
  DaOnGil/presentation/src/main/res/layout/activity_report.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX, 기능

#97 [#87] 일정 후기 작성 화면 api 연결
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/PlanDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/request/ScheduleReviewRequest.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/briefScheduleInfo/BriefScheduleInfoResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/briefScheduleInfo/Data.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/PlanRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/PlanService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/schedule/BriefScheduleInfo.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/schedule/NewScheduleReview.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/schedule/ReviewImg.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/PlanRepository.kt
  DaOnGil/presentation/src/main/AndroidManifest.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/MyScheduleActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/WriteScheduleReviewActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/adapter/WriteReviewImageAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/vm/WriteScheduleReviewViewModel.kt
  DaOnGil/presentation/src/main/res/drawable/selector_review_public_background.xml
  DaOnGil/presentation/src/main/res/drawable/selector_review_public_text.xml
  DaOnGil/presentation/src/main/res/layout/activity_write_schedule_review.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX, 기능

#107 [#105] merge 하면서 생긴 오류 수정
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/request/NewPlanRequest.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/request/ScheduleReviewRequest.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/PlanService.kt
Labels: 버그

#101 [#94] 홈 관광지 관련 화면 이동 연결
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/DetailActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/model/HomeViewPagerPage.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/model/ReviewInfo.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/HomeVPAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/res/navigation/bottom_navigation_graph.xml
Labels: 기능

#110 [#98] 일정 후기 수정 기능 구현
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/PlanDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/request/ModifyScheduleReviewRequest.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/PlanRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/PlanService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/schedule/ModifiedScheduleReview.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/schedule/ReviewImage.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/schedule/ScheduleReviewInfo.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/PlanRepository.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/usecase/plan/GetScheduleReviewInfoUseCase.kt
  DaOnGil/presentation/src/main/AndroidManifest.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/MyScheduleActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedule/ScheduleDetailActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/ModifyScheduleReviewActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/adapter/ModifyReviewImageAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/vm/ModifyScheduleReviewViewModel.kt
  DaOnGil/presentation/src/main/res/layout/activity_modify_schedule_review.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX, 기능

#113 [#100] 관광 정보 버그 수정 및 관광지 상세보기 화면 이동
  DaOnGil/.idea/deploymentTargetSelector.xml
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/searchplace/auto_complete_keyword/Data.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/searchplace/list/PlaceRes.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/RecentlySearchKeywordRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/PlaceService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/Place.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/area/AreaCode.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/area/SigunguCode.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/search/AutoCompleteKeyword.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/search/ListSearchResult.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/search/RecentlySearchKeyword.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/RecentlySearchKeywordRepository.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/delegate/NetworkErrorDelegate.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/adapter/SearchResultAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/adapter/SearchSuggestionsAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/fragment/OnSearchFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/fragment/SearchResultFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/viewholder/SearchSuggestionsViewHolder.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/vm/KeywordSearchViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/ListSearchAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/viewholder/PlaceHighViewHolder.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/SearchListFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/model/ListSearchUIModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/search/SearchListViewModel.kt
  DaOnGil/presentation/src/main/res/drawable/progress_icon.xml
  DaOnGil/presentation/src/main/res/layout/fragment_search_list.xml
  DaOnGil/presentation/src/main/res/layout/item_list_search_category.xml
  DaOnGil/presentation/src/main/res/layout/item_list_search_sort.xml
  DaOnGil/presentation/src/main/res/layout/item_no_place.xml
Labels: 기능

#95 [#93] 공개일정 둘러보기 더보기 화면 구현
  DaOnGil/presentation/src/main/AndroidManifest.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/GlideExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/RvExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/ScheduleMyAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/SchedulePublicAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/adapter/MyReviewImageRVAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedule/PublicScheduleActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedule/ScheduleDetailActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedule/adapter/PublicScheduleAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedule/vm/PublicScheduleViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/adapter/FormConfirmPlaceAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/adapter/FormSearchResultAdapter.kt
  DaOnGil/presentation/src/main/res/layout/activity_public_schedule.xml
  DaOnGil/presentation/src/main/res/layout/item_public_schedule.xml
Labels: UI/UX, 기능

#111 [#109] 관광지 후기목록 게스트ver api 연결
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/PlaceDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/placereviewlistguest/Data.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/placereviewlistguest/MyPlaceReviewGuest.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/placereviewlistguest/PlaceReviewResponseGuest.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/PlaceRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/PlaceService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/PlaceRepository.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/DetailActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/ReviewListActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/model/ReviewInfo.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/vm/ReviewListViewModel.kt
Labels: 기능

#124 [#118] 내 일정 목록 페이징 오류 수정
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/myScheduleUpcoming/MyUpcomingsResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/plan/myScheduleUpcoming/PlanRes.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/MyScheduleActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/vm/MyScheduleViewModel.kt
Labels: 버그

#123 [#120] 관광지 리뷰 전체 조회 데이터 추가
  DaOnGil/data/src/main/java/kr/tekit/lion/data/database/MainDatabase.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/database/dao/AreaCodeDao.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/database/dao/SigunguCodeDao.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/AreaCodeDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/SigunguCodeDatasource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/placereviewlist/Data.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/placereviewlist/PlaceReviewResponse.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/placereviewlistguest/Data.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/placereviewlistguest/PlaceReviewResponseGuest.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/AreaCodeRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/SigunguCodeRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/PlaceService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/placereviewlist/PlaceReviewInfo.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/AreaCodeRepository.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/SigunguCodeRepository.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/ReviewListActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/home/HomeViewModel.kt
Labels: 버그, 기능

#121 [#108] 관광지 상세보기 수정하기 화면 이동 구현
  DaOnGil/.idea/other.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/DetailActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/model/ReviewInfo.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/MyReviewActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/fragment/MyReviewFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/fragment/MyReviewModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/vm/MyReviewViewModel.kt
Labels: 기능

#129 [#114] 로그아웃 api 연결, 이슈 다수 수정
  DaOnGil/.idea/deploymentTargetSelector.xml
  DaOnGil/data/src/main/java/kr/tekit/lion/data/database/AppSettings.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/ActivationDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/di/DataSourceModule.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/di/RepositoryModule.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/ActivationRepositoryImpl.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/ConcernType.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/ActivationRepository.kt
  DaOnGil/presentation/src/main/AndroidManifest.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/delegate/NetworkErrorDelegate.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/fragment/OnSearchFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/fragment/SearchResultFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/vm/KeywordSearchViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/vm/SearchResultViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/OnBoardingActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/fragment/LoginFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/fragment/SelectInterestFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/vm/InterestViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/vm/LoginViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/vm/OnBoardingViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/dialog/ModeSettingDialog.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/SearchListFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/home/HomeViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/myinfo/MyInfoMainViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/search/SearchListViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/fragment/IceModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/fragment/MyInfoFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/fragment/PersonalInfoModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/model/ImgModifyState.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/vm/MyInfoViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/splash/SplashActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/splash/vm/SplashViewModel.kt
  DaOnGil/presentation/src/main/res/drawable/img_no_search_result.gif
  DaOnGil/presentation/src/main/res/layout/activity_on_boarding.xml
  DaOnGil/presentation/src/main/res/layout/fragment_my_info.xml
  DaOnGil/presentation/src/main/res/layout/fragment_my_info_main.xml
  DaOnGil/presentation/src/main/res/layout/fragment_personal_info_modify.xml
  DaOnGil/presentation/src/main/res/layout/fragment_select_interest.xml
  DaOnGil/presentation/src/main/res/navigation/login_navigation_graph.xml
  DaOnGil/presentation/src/main/res/raw/splash_video.mp4
Labels: 버그, 기능, 리팩토링

#130 [#128] 관심유형 프로그래스바 및 에러처리 추가
  DaOnGil/data/schemas/kr.tekit.lion.data.database.MainDatabase/3.json
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/concerntype/fragment/ConcernTypeFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/concerntype/vm/ConcernTypeViewModel.kt
  DaOnGil/presentation/src/main/res/layout/fragment_concern_type.xml
Labels: UI/UX, 기능

#126 [#119] 일정 상세보기 리뷰 확대 기능 추가
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedule/ScheduleDetailActivity.kt
  DaOnGil/presentation/src/main/res/layout/activity_schedule_detail.xml
Labels: UI/UX, 기능

#135 [#125] 홈 메인화면 프로그래스바 추가
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/home/HomeViewModel.kt
  DaOnGil/presentation/src/main/res/layout/fragment_home_main.xml
Labels: UI/UX, 기능

#140 [#134] 일정 메인화면 프로그래스바 및 에러 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/schedule/ScheduleMainViewModel.kt
  DaOnGil/presentation/src/main/res/layout/fragment_schedule_main.xml
Labels: UI/UX, 기능

#141 [#137] 홈 메인화면 에러처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/res/layout/fragment_home_main.xml
Labels: UI/UX, 기능

#138 [#127] 내 일정 목록 프로그래스바 추가
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/MyScheduleActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/vm/MyScheduleViewModel.kt
  DaOnGil/presentation/src/main/res/layout/activity_my_schedule.xml
Labels: UI/UX, 기능

#144 [#139] 일정 - 여행지 검색 화면 프로그래스바 에러처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/FormSearchFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/vm/ScheduleFormViewModel.kt
  DaOnGil/presentation/src/main/res/layout/fragment_form_search.xml
Labels: UI/UX, 기능

#147 [#142] 시스템 고대비 테마 설정 후 테마 설정 다이얼로그 클릭시 앱 크래시 수정
  DaOnGil/data/src/main/java/kr/tekit/lion/data/database/AppSettings.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/dialog/ThemeGuideDialog.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/dialog/ThemeSettingDialog.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/home/HomeViewModel.kt
  DaOnGil/presentation/src/main/res/drawable/image_theme_guide.png
  DaOnGil/presentation/src/main/res/layout/dialog_theme_guide.xml
Labels: 버그

#152 [#149] 사용자 로그아웃 api 구현
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/AuthDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/AuthRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/AuthAuthenticator.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/AuthService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/AuthRepository.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/fragment/LoginFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/vm/LoginViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/myinfo/MyInfoMainViewModel.kt
Labels: 기능, 리팩토링

#132 [#131] 마이페이지 북마크 프로그래스바 및 에러 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/bookmark/BookmarkActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/bookmark/vm/BookmarkViewModel.kt
  DaOnGil/presentation/src/main/res/layout/activity_bookmark.xml
  DaOnGil/presentation/src/main/res/layout/fragment_concern_type.xml
Labels: UI/UX, 기능

#136 [#133] 나의 여행지 후기 프로그래스바 및 에러 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/fragment/MyReviewFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/vm/MyReviewViewModel.kt
  DaOnGil/presentation/src/main/res/layout/fragment_my_review.xml
Labels: UI/UX, 기능

#150 [#148] 공개일정 더보기 화면 프로그래스바 및 에러 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedule/PublicScheduleActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedule/vm/PublicScheduleViewModel.kt
  DaOnGil/presentation/src/main/res/layout/activity_public_schedule.xml
Labels: UI/UX, 기능

#155 [#154] 일정 등록 api 프로그래스바 및 에러 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/ScheduleConfirmFormFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/vm/ScheduleFormViewModel.kt
  DaOnGil/presentation/src/main/res/layout/fragment_schedule_confirm_form.xml
Labels: UI/UX, 기능

#157 [#156] 여행 후기 등록 api 프로그래스바 및 에러 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/WriteScheduleReviewActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/vm/WriteScheduleReviewViewModel.kt
  DaOnGil/presentation/src/main/res/layout/activity_write_schedule_review.xml
Labels: UI/UX, 기능

#165 [#158] 여행 후기 수정 api 프로그래스바 및 에러 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/ModifyScheduleReviewActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/vm/ModifyScheduleReviewViewModel.kt
  DaOnGil/presentation/src/main/res/layout/activity_modify_schedule_review.xml
Labels: UI/UX, 기능

#167 [#161] 관광지 리뷰 신고하기 연결
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/DetailActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/ReviewListActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/adapter/DetailReviewRVAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/adapter/ReviewListRVAdapter.kt
Labels: 기능

#169 [#161] 관광지 리뷰 신고하기 연결
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/DetailActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/ReviewListActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/adapter/DetailReviewRVAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/adapter/ReviewListRVAdapter.kt
Labels: 기능

#170 [#163] 북마크 업데이트 에러 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/bookmark/BookmarkActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/bookmark/vm/BookmarkViewModel.kt
  DaOnGil/presentation/src/main/res/layout/activity_bookmark.xml
  DaOnGil/presentation/src/main/res/layout/fragment_concern_type.xml
  DaOnGil/presentation/src/main/res/layout/fragment_my_review.xml
Labels: 기능

#177 [#172] 나의 여행지 후기 목록 신고 승인 여부 처리
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/myreview/MyPlaceReviewDto.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/dto/response/myreview/MyPlaceReviewResponse.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/MyPlaceReviewInfo.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/model/ReviewInfo.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/adapter/MyReviewRVAdapter.kt
  DaOnGil/presentation/src/main/res/layout/item_my_review.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX, 기능

#174 [#171] 관광지 상세보기 에러 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/DetailActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/vm/DetailViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/res/layout/activity_detail.xml
Labels: UI/UX, 기능

#176 [#175] 관광지 리뷰 전체보기 에러처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/ReviewListActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/vm/ReviewListViewModel.kt
  DaOnGil/presentation/src/main/res/layout/activity_review_list.xml
Labels: UI/UX, 기능

#168 [164] 키워드 검색화면 에러 처리
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/exception/HttpError.kt
  DaOnGil/presentation/src/main/AndroidManifest.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/delegate/NetworkErrorDelegate.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/KeywordSearchActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/fragment/OnSearchFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/fragment/SearchResultFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/vm/KeywordSearchViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/observer/ConnectivityObserver.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/observer/NetworkConnectivityObserver.kt
Labels: 기능

#184 [#183] 홈 에러처리 화면 수정
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/HomeMainFragment.kt
Labels: 리팩토링

#182 [#178] 홈 위치권한 거절 시 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/home/HomeViewModel.kt
Labels: 기능, 리팩토링

#189 [#185] 관광지 상세보기 리뷰 작성 에러 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/WriteReviewActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/vm/DetailViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/vm/WriteReviewViewModel.kt
Labels: 기능

#188 [#166] 일정 메인화면 및 상세보기 오류 수정
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/PlanDataSource.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/schedule/ScheduleMainViewModel.kt
Labels: UI/UX, 기능, 리팩토링

#193 [#191] 관광지 편의정보 아이콘 수정
  DaOnGil/presentation/src/main/res/drawable-night/info_icon.xml
  DaOnGil/presentation/src/main/res/drawable/info_icon.xml
  DaOnGil/presentation/src/main/res/layout/item_detail_service_info.xml
Labels: UI/UX, 리팩토링

#186 [#181] 개인 정보 및 응급 정보 수정 UI 수정
  DaOnGil/presentation/src/main/res/layout/fragment_ice_modify.xml
  DaOnGil/presentation/src/main/res/layout/fragment_personal_info_modify.xml
Labels: UI/UX, 리팩토링

#196 [#194] 홈 지역코드 null값 버그
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/schedule/ScheduleMainViewModel.kt
Labels: 버그

#201 [#200] 시군구 코드 쿼리, 엔티티 수정
  DaOnGil/data/src/main/java/kr/tekit/lion/data/database/dao/SigunguCodeDao.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/database/entity/SigunguCodeEntity.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/SigunguCodeDatasource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/SigunguCodeRepositoryImpl.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/SigunguCodeRepository.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/home/HomeViewModel.kt
Labels: 버그

#202 [#192] 홈화면 위치 naver map api로 수정
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/home/HomeViewModel.kt
Labels: 버그, UI/UX, 기능, 리팩토링

#198 [#197] 관광지 상세보기 북마크 에러처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/DetailActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/vm/DetailViewModel.kt
Labels: 기능

#195 [#187] 나의 여행지 후기 및 삭제 수정 에러 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/fragment/MyReviewFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/fragment/MyReviewModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/vm/MyReviewViewModel.kt
  DaOnGil/presentation/src/main/res/layout/fragment_my_review_modify.xml
Labels: UI/UX, 기능

#207 [#206] 일정 등록 화면에서 등록된 일정이 없는 경우 viewholder 추가
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/adapter/FormConfirmPlaceAdapter.kt
  DaOnGil/presentation/src/main/res/layout/item_form_empty.xml
Labels: UI/UX

#208 [#190] 나의 개인 정보 네트워크 에러 처리
  DaOnGil/data/src/main/java/kr/tekit/lion/data/database/MainDatabase.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/ContextExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/myinfo/MyInfoMainViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/fragment/IceModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/fragment/MyInfoFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/fragment/PersonalInfoModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/vm/MyInfoViewModel.kt
  DaOnGil/presentation/src/main/res/layout/fragment_ice_modify.xml
  DaOnGil/presentation/src/main/res/layout/fragment_my_info.xml
  DaOnGil/presentation/src/main/res/layout/fragment_my_info_main.xml
  DaOnGil/presentation/src/main/res/layout/fragment_personal_info_modify.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: 기능

#205 [#199] 후기 수정 화면에서 기존 후기 불러오는 방식 변경
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/usecase/plan/GetScheduleReviewInfoUseCase.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedule/ScheduleDetailActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedule/vm/ScheduleDetailViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/ModifyScheduleReviewActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/model/OriginalScheduleReviewInfo.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/vm/ModifyScheduleReviewViewModel.kt
Labels: 기능, 리팩토링

#212 [#211] 내 일정 목록과 등록 화면 연결 textview height 수정
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/MyScheduleActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedule/ResultCode.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/ScheduleConfirmFormFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/WriteScheduleReviewActivity.kt
  DaOnGil/presentation/src/main/res/layout/activity_my_schedule.xml
Labels: UI/UX, 기능

#213 [#210] 관광 정보 지도 검색 프로그래스바 적용
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/SearchListFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/SearchMapFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/SearchPlaceMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/home/HomeViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/search/SearchMapViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/search/SearchViewModel.kt
  DaOnGil/presentation/src/main/res/layout/fragment_search_map.xml
Labels: 기능

#215 [#214] 앱 약관 화면 추가 완료
  DaOnGil/presentation/src/main/AndroidManifest.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/setting/PolicyActivity.kt
  DaOnGil/presentation/src/main/res/layout/activity_policy.xml
  DaOnGil/presentation/src/main/res/layout/fragment_my_info_main.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: 기능

#204 [#146] 일정 상세보기 프로그래스바 및 에러 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/delegate/NetworkErrorDelegate.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/schedule/ScheduleMainViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedule/ScheduleDetailActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedule/vm/ScheduleDetailViewModel.kt
  DaOnGil/presentation/src/main/res/layout/activity_schedule_detail.xml
  DaOnGil/presentation/src/main/res/layout/fragment_schedule_main.xml
Labels: UI/UX, 기능, 리팩토링

#217 [#216] 앱 출시전 기타 사항 수정
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/ic_app_logo-playstore.png
  DaOnGil/app/src/main/ic_app_main_logo-playstore.png
  DaOnGil/app/src/main/ic_app_main_logo_test-playstore.png
  DaOnGil/app/src/main/ic_launcher-playstore.png
  DaOnGil/app/src/main/res/drawable/ic_app_main_logo_background.xml
  DaOnGil/app/src/main/res/drawable/ic_app_main_logo_foreground.xml
  DaOnGil/app/src/main/res/drawable/ic_launcher_background.xml
  DaOnGil/app/src/main/res/drawable/ic_launcher_foreground.xml
  DaOnGil/app/src/main/res/mipmap-anydpi-v26/ic_app_main_logo.xml
  DaOnGil/app/src/main/res/mipmap-anydpi-v26/ic_app_main_logo_round.xml
  DaOnGil/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  DaOnGil/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  DaOnGil/app/src/main/res/mipmap-hdpi/ic_app_main_logo.webp
  DaOnGil/app/src/main/res/mipmap-hdpi/ic_app_main_logo_foreground.webp
  DaOnGil/app/src/main/res/mipmap-hdpi/ic_app_main_logo_round.webp
  DaOnGil/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  DaOnGil/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  DaOnGil/app/src/main/res/mipmap-mdpi/ic_app_main_logo.webp
  DaOnGil/app/src/main/res/mipmap-mdpi/ic_app_main_logo_foreground.webp
  DaOnGil/app/src/main/res/mipmap-mdpi/ic_app_main_logo_round.webp
  DaOnGil/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  DaOnGil/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  DaOnGil/app/src/main/res/mipmap-xhdpi/ic_app_main_logo.webp
  DaOnGil/app/src/main/res/mipmap-xhdpi/ic_app_main_logo_foreground.webp
  DaOnGil/app/src/main/res/mipmap-xhdpi/ic_app_main_logo_round.webp
  DaOnGil/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  DaOnGil/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  DaOnGil/app/src/main/res/mipmap-xxhdpi/ic_app_main_logo.webp
  DaOnGil/app/src/main/res/mipmap-xxhdpi/ic_app_main_logo_foreground.webp
  DaOnGil/app/src/main/res/mipmap-xxhdpi/ic_app_main_logo_round.webp
  DaOnGil/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  DaOnGil/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  DaOnGil/app/src/main/res/mipmap-xxxhdpi/ic_app_main_logo.webp
  DaOnGil/app/src/main/res/mipmap-xxxhdpi/ic_app_main_logo_foreground.webp
  DaOnGil/app/src/main/res/mipmap-xxxhdpi/ic_app_main_logo_round.webp
  DaOnGil/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  DaOnGil/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  DaOnGil/app/src/main/res/values/strings.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/presentation/src/main/res/layout/fragment_my_info_main.xml
Labels: UI/UX, 기능

#218 [#216] 앱 출시전 기타 사항 수정2
  DaOnGil/app/build.gradle.kts
  DaOnGil/presentation/src/main/res/layout/fragment_ice_modify.xml
  DaOnGil/presentation/src/main/res/layout/fragment_personal_info_modify.xml
Labels: 리팩토링

#222 [#221] 카카오 로그인 오류 수정
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/AuthDataSource.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/vm/LoginViewModel.kt
  DaOnGil/presentation/src/main/res/layout/fragment_login.xml
Labels: 버그, 리팩토링

#225 [#219] 관광 정보 화면 바텀시트 탭 전환시 검색결과가 사라지는 버그 수정
  DaOnGil/presentation/src/main/AndroidManifest.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/SearchListFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/model/ListOptionState.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/model/MapOptionState.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/search/SearchListViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/search/SearchMapViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/DeleteUserActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/setting/PolicyActivity.kt
Labels: 버그

#224 [#223] 홈화면에서 특별시 지역 처리 수정
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/home/HomeViewModel.kt
Labels: UI/UX, 기능, 리팩토링

#228 [#226] 관광공사 코드 API 호출 실패시 재시도 로직 추가
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/splash/SplashActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/splash/vm/SplashViewModel.kt
Labels: 버그

#231 [#230] 관심 유형 네트워크 에러 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/concerntype/fragment/ConcernTypeFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/concerntype/fragment/ConcernTypeModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/concerntype/vm/ConcernTypeViewModel.kt
  DaOnGil/presentation/src/main/res/layout/fragment_concern_type.xml
Labels: 기능

#233 [#232] 북마크 목록 네트워크 에러 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/bookmark/BookmarkActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/bookmark/vm/BookmarkViewModel.kt
Labels: 기능

#235 [#234] 나의 여행지 후기 네트워크 에러 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/fragment/MyReviewFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/fragment/MyReviewModifyFragment.kt
Labels: 기능

#237 [#236] 관심 유형 네트워크 에러 처리 데이터 재요청
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/concerntype/fragment/ConcernTypeFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/concerntype/vm/ConcernTypeViewModel.kt
Labels: 기능

#240 [#229] 로그인 API 수정, 불필요한 코드 제거
  DaOnGil/.idea/caches/deviceStreaming.xml
  DaOnGil/data/schemas/kr.tekit.lion.data.database.MainDatabase/4.json
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/AuthDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/mapper/MapperExtensions.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/AuthRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/AuthService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/AuthRepository.kt
  DaOnGil/gradle/libs.versions.toml
  DaOnGil/presentation/build.gradle.kts
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/Permissions.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/fragment/LoginFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/vm/LoginViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/viewholder/AreaViewHolder.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/viewholder/CategoryViewHolder.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/viewholder/SigunguViewHolder.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/SearchMapFragment.kt
Labels: 리팩토링

#242 [#241] 신고하기 네트워크 에러 처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/report/ReportActivity.kt
Labels: 기능

#244 [#243] 북마크 목록 UI 접근성 개선
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/bookmark/BookmarkActivity.kt
  DaOnGil/presentation/src/main/res/drawable-night/empty_view_long.xml
  DaOnGil/presentation/src/main/res/drawable/empty_view_long.xml
  DaOnGil/presentation/src/main/res/layout/activity_bookmark.xml
  DaOnGil/presentation/src/main/res/layout/item_place_bookmark.xml
  DaOnGil/presentation/src/main/res/layout/item_plan_bookmark.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
  DaOnGil/presentation/src/main/res/values/styles.xml
Labels: UI/UX

#246 [#239] 내 일정 목록 네트워크 재연결 시 데이터 요청, 접근성 개선
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/MyScheduleActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/vm/MyScheduleViewModel.kt
  DaOnGil/presentation/src/main/res/layout/activity_my_schedule.xml
Labels: UI/UX, 기능

#248 [#247] 관심 유형 UI 접근성 개선
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/concerntype/fragment/ConcernTypeFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/concerntype/fragment/ConcernTypeModifyFragment.kt
  DaOnGil/presentation/src/main/res/layout/fragment_concern_type.xml
  DaOnGil/presentation/src/main/res/layout/fragment_concern_type_modify.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX

#251 [#238] 관광지 상세보기 UI 수정
  DaOnGil/presentation/src/main/res/drawable-night/detail_address_icon.xml
  DaOnGil/presentation/src/main/res/drawable-night/detail_call_icon.xml
  DaOnGil/presentation/src/main/res/drawable-night/detail_link_icon.xml
  DaOnGil/presentation/src/main/res/drawable-night/detail_review_modify_icon.xml
  DaOnGil/presentation/src/main/res/drawable-night/info_icon.xml
  DaOnGil/presentation/src/main/res/drawable/detail_address_icon.xml
  DaOnGil/presentation/src/main/res/drawable/detail_call_icon.xml
  DaOnGil/presentation/src/main/res/drawable/detail_link_icon.xml
  DaOnGil/presentation/src/main/res/drawable/detail_review_modify_icon.xml
  DaOnGil/presentation/src/main/res/drawable/info_icon.xml
  DaOnGil/presentation/src/main/res/layout/activity_detail.xml
  DaOnGil/presentation/src/main/res/layout/item_detail_service_info.xml
  DaOnGil/presentation/src/main/res/values/dimens.xml
Labels: UI/UX, 리팩토링
