Repository Journey-Together/DaOnGil_CleanArchitecture, pull requests merged in 2024-08, with the labels that each got.

#22 [ Feat] 지도 검색 api 재구현
  DaOnGil/.idea/deploymentTargetSelector.xml
  DaOnGil/.idea/other.xml
  DaOnGil/gradle/libs.versions.toml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/ListSearchAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/bottomsheet/PlaceBottomSheet.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/SearchListFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/SearchMapFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/SearchPlaceMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/model/ListSearchUIModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/model/MapPlaceModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/model/SharedOptionState.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/search/SearchListViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/search/SearchMapViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/search/SharedViewModel.kt
Labels: 기능, 리팩토링

#26 [Refactor] 2차 전체 코드 리팩토링 및 리사이클러뷰 성능 개선
  DaOnGil/.idea/deploymentTargetSelector.xml
  DaOnGil/.idea/misc.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/ListSearchAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/viewholder/CategoryViewHolder.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/SearchListFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/SearchMapFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/search/SearchMapViewModel.kt
  DaOnGil/presentation/src/main/res/drawable/sv_hearing_impaired_unselected_icon.xml
  DaOnGil/presentation/src/main/res/layout/fragment_search_list.xml
  DaOnGil/presentation/src/main/res/layout/fragment_search_place_main.xml
  DaOnGil/presentation/src/main/res/layout/item_list_search_area.xml
  DaOnGil/presentation/src/main/res/layout/item_list_search_category.xml
  DaOnGil/presentation/src/main/res/layout/item_list_search_sigungu.xml
  DaOnGil/presentation/src/main/res/layout/item_no_place.xml
  DaOnGil/presentation/src/main/res/layout/item_place_high.xml
  DaOnGil/presentation/src/main/res/values/colors.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
  DaOnGil/presentation/src/main/res/values/themes.xml
Labels: 리팩토링

#28 [Refactor] 3차 리사이클러뷰 성능 개선
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/SearchListFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/search/SearchListViewModel.kt
Labels: 기능, 리팩토링

#37 [Feat] 사용자 프로필 화면 접근성 개선
  DaOnGil/data/src/main/java/kr/tekit/lion/data/common/NetworkResultHandler.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/MemberDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/MemberRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/PlaceRepositoryImpl.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/exception/HttpError.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/exception/NetworkError.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/exception/Result.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/model/NetworkError.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/MemberRepository.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/PlaceRepository.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/delegate/NetworkErrorDelegate.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/ContextExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/StringExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/TextViewExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/vm/KeywordSearchViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/vm/InterestViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/myinfo/MyInfoMainViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/search/SearchListViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/fragment/IceModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/fragment/MyInfoFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/fragment/PersonalInfoModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/vm/MyInfoViewModel.kt
  DaOnGil/presentation/src/main/res/drawable/ic_arrow_drop_down.xml
  DaOnGil/presentation/src/main/res/drawable/ic_read_info.xml
  DaOnGil/presentation/src/main/res/drawable/ic_read_script.xml
  DaOnGil/presentation/src/main/res/drawable/spinner_background.xml
  DaOnGil/presentation/src/main/res/layout/fragment_ice_modify.xml
  DaOnGil/presentation/src/main/res/layout/fragment_my_info.xml
  DaOnGil/presentation/src/main/res/layout/fragment_my_info_main.xml
  DaOnGil/presentation/src/main/res/layout/fragment_personal_info_modify.xml
  DaOnGil/presentation/src/main/res/menu/menu_read_ice_script.xml
  DaOnGil/presentation/src/main/res/menu/menu_read_my_info_script.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: 기능

#38 [Rector] 사용자 프로필 화면 접근성 수정
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/TextViewExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/fragment/IceModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/fragment/MyInfoFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/fragment/PersonalInfoModifyFragment.kt
  DaOnGil/presentation/src/main/res/layout/fragment_ice_modify.xml
  DaOnGil/presentation/src/main/res/layout/fragment_my_info.xml
  DaOnGil/presentation/src/main/res/layout/fragment_my_info_main.xml
  DaOnGil/presentation/src/main/res/values-night/colors.xml
Labels: 기능, 리팩토링

#42 [Feat] 관광지 검색화면 접근성 개발
  DaOnGil/presentation/src/main/AndroidManifest.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/ViewExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/viewholder/AreaViewHolder.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/viewholder/CategoryViewHolder.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/viewholder/ItemCountViewHolder.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/viewholder/PlaceHighViewHolder.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/viewholder/SigunguViewHolder.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/bottomsheet/CategoryBottomSheet.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/SearchPlaceMainFragment.kt
  DaOnGil/presentation/src/main/res/drawable/ic_read_script.xml
  DaOnGil/presentation/src/main/res/layout/fragment_search_place_main.xml
  DaOnGil/presentation/src/main/res/layout/item_list_search_area.xml
  DaOnGil/presentation/src/main/res/layout/item_place_high.xml
  DaOnGil/presentation/src/main/res/values-night/colors.xml
  DaOnGil/presentation/src/main/res/values/colors.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
  DaOnGil/presentation/src/main/res/values/styles.xml
Labels: UI/UX, 기능

#40 [#36] 마이페이지 관심 유형 구현
  DaOnGil/.idea/deploymentTargetSelector.xml
  DaOnGil/.idea/navEditor.xml
  DaOnGil/.idea/other.xml
  DaOnGil/presentation/src/main/AndroidManifest.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/concerntype/ConcernTypeActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/concerntype/fragment/ConcernTypeFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/concerntype/fragment/ConcernTypeModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/concerntype/vm/ConcernTypeViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/presentation/src/main/res/navigation/nav_concern_type_graph.xml
Labels: UI/UX, 기능

#46 [#45] import 오류
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/concerntype/vm/ConcernTypeViewModel.kt
Labels: 버그

#50 [#49] 응급지원 메인 화면 구현 및 activity 연결
  DaOnGil/presentation/src/main/AndroidManifest.xml
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/emergency/EmergencyMapActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/emergency/PharmacyMapActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/emergency/adapter/EmergencyBottomAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/emergency/fragment/EmergencyAreaDialog.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/emergency/fragment/EmergencyBottomSheet.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/EmergencyMainFragment.kt
  DaOnGil/presentation/src/main/res/layout/activity_emergency_map.xml
  DaOnGil/presentation/src/main/res/layout/activity_pharmacy_map.xml
  DaOnGil/presentation/src/main/res/layout/dialog_emergency_area.xml
  DaOnGil/presentation/src/main/res/layout/emergency_bottom_sheet_layout.xml
  DaOnGil/presentation/src/main/res/layout/item_emergency_bottom.xml
Labels: UI/UX, 기능
