Repository Journey-Together/DaOnGil_CleanArchitecture, pull requests merged in 2024-10, with the labels that each got.

#254 [#250] 나의 여행지 후기 UI 접근성 개선
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/PhotoDialog.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/adapter/MyReviewRVAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/fragment/MyReviewFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myreview/fragment/MyReviewModifyFragment.kt
  DaOnGil/presentation/src/main/res/drawable-night/star_filled_icon.xml
  DaOnGil/presentation/src/main/res/drawable-night/star_half_filled_icon.xml
  DaOnGil/presentation/src/main/res/layout/fragment_my_review.xml
  DaOnGil/presentation/src/main/res/layout/fragment_my_review_modify.xml
  DaOnGil/presentation/src/main/res/layout/item_my_review.xml
  DaOnGil/presentation/src/main/res/layout/item_my_review_header.xml
  DaOnGil/presentation/src/main/res/layout/item_review_big_image.xml
  DaOnGil/presentation/src/main/res/layout/item_review_write_image.xml
  DaOnGil/presentation/src/main/res/values-night/colors.xml
  DaOnGil/presentation/src/main/res/values/colors.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX

#258 [#256] 신고하기 UI 접근성 개선
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/report/ReportActivity.kt
  DaOnGil/presentation/src/main/res/layout/activity_report.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX

#255 [#253] 일정 메인 화면 내 일정 목록 접근성 개선
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/DateFormatExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/adapter/ScheduleMyAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/MyScheduleActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/adapter/MyScheduleElapsedAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myschedule/adapter/MyScheduleUpcomingAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/FormDateFormat.kt
  DaOnGil/presentation/src/main/res/layout/fragment_schedule_main.xml
  DaOnGil/presentation/src/main/res/layout/item_my_schedule_elapsed.xml
  DaOnGil/presentation/src/main/res/layout/item_my_schedule_upcoming.xml
  DaOnGil/presentation/src/main/res/layout/row_schedule_my.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: 버그, UI/UX

#260 [#252] 홈 메인화면 에러처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/HomeMainFragment.kt
Labels: 기능

#262 [#261] 관광지 상세보기 네트워크 에러처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/DetailActivity.kt
Labels: 기능

#270 [#249] 회원 탈퇴 처리 구현
  DaOnGil/data/src/main/java/kr/tekit/lion/data/datasource/AuthDataSource.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/repository/AuthRepositoryImpl.kt
  DaOnGil/data/src/main/java/kr/tekit/lion/data/service/AuthService.kt
  DaOnGil/domain/src/main/java/kr/tekit/lion/domain/repository/AuthRepository.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/DeleteUserActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/vm/DeleteUserViewModel.kt
  DaOnGil/presentation/src/main/res/layout/fragment_home_main.xml
  DaOnGil/presentation/src/main/res/layout/item_tourist_recommend.xml
Labels: 기능

#267 [#266] 관광지 리뷰 작성 에러 수정
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/WriteReviewActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/vm/WriteReviewViewModel.kt
Labels: 버그

#264 [#263] 관광지 리뷰 네트워크 에러처리
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/ActivityExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/ViewExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/ReviewListActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/home/WriteReviewActivity.kt
Labels: 기능

#265 [#259] 관심 유형 및 북마크 접근성 수정
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/bookmark/adapter/BookmarkDisabilityRvAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/bookmark/adapter/PlaceBookmarkRVAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/bookmark/adapter/PlanBookmarkRVAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/concerntype/fragment/ConcernTypeFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/concerntype/fragment/ConcernTypeModifyFragment.kt
  DaOnGil/presentation/src/main/res/layout/fragment_concern_type.xml
  DaOnGil/presentation/src/main/res/layout/fragment_concern_type_modify.xml
  DaOnGil/presentation/src/main/res/layout/item_place_bookmark.xml
  DaOnGil/presentation/src/main/res/layout/item_plan_bookmark.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX, 리팩토링

#272 [#268] 홈 위치 설정 버그
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/home/HomeViewModel.kt
  DaOnGil/presentation/src/main/res/drawable-night/highcontrast_icon.xml
  DaOnGil/presentation/src/main/res/drawable/highcontrast_icon.xml
  DaOnGil/presentation/src/main/res/values/styles.xml
Labels: 버그

#273 [#271] 난독화 적용 완료
  DaOnGil/.idea/deploymentTargetSelector.xml
  DaOnGil/app/build.gradle.kts
  DaOnGil/app/proguard-rules.pro
  DaOnGil/presentation/build.gradle.kts
Labels: 기능

#280 [#279] 최초 유저 판별 데이터 리딩시 앱 크래시 수정
  DaOnGil/app/build.gradle.kts
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/home/HomeViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/splash/SplashActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/splash/vm/SplashViewModel.kt
  DaOnGil/presentation/src/main/res/layout/activity_keyword_search.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: 버그

#275 [#269] 새로운 일정 작성 화면 접근성 개선
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/adapter/FormBookmarkedPlacesAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/adapter/FormConfirmPlaceAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/adapter/FormPlaceAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/adapter/FormScheduleAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/adapter/FormSearchResultAdapter.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/NameAndPeriodFormFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/ScheduleConfirmFormFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/ScheduleDetailsFormFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/vm/ScheduleFormViewModel.kt
  DaOnGil/presentation/src/main/res/layout/fragment_form_search.xml
  DaOnGil/presentation/src/main/res/layout/fragment_name_and_period_form.xml
  DaOnGil/presentation/src/main/res/layout/fragment_schedule_confirm_form.xml
  DaOnGil/presentation/src/main/res/layout/fragment_schedule_details_form.xml
  DaOnGil/presentation/src/main/res/layout/item_form_bookmarked_places.xml
  DaOnGil/presentation/src/main/res/layout/item_form_confirm.xml
  DaOnGil/presentation/src/main/res/layout/item_form_empty.xml
  DaOnGil/presentation/src/main/res/layout/item_form_place.xml
  DaOnGil/presentation/src/main/res/layout/item_form_schedule.xml
  DaOnGil/presentation/src/main/res/layout/item_form_search_result.xml
  DaOnGil/presentation/src/main/res/values-night/colors.xml
  DaOnGil/presentation/src/main/res/values/colors.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX, 기능

#282 [#257] 일정 관련 에러 처리 수정
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedule/PublicScheduleActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedule/ScheduleDetailActivity.kt
Labels: 기능

#283 [#276] 일정 수정화면 접근성 개선
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/ModifyNamePeriodFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/ModifyScheduleConfirmFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/fragment/ModifyScheduleDetailsFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/scheduleform/vm/ModifyScheduleFormViewModel.kt
  DaOnGil/presentation/src/main/res/layout/fragment_modify_name_period.xml
  DaOnGil/presentation/src/main/res/layout/fragment_modify_schedule_confirm.xml
  DaOnGil/presentation/src/main/res/layout/fragment_modify_schedule_details.xml
Labels: UI/UX, 기능

#285 [#277] 일정 후기 화면 접근성 개선
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/IntExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/WriteScheduleReviewActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/vm/WriteScheduleReviewViewModel.kt
  DaOnGil/presentation/src/main/res/drawable/selector_review_public_text.xml
  DaOnGil/presentation/src/main/res/layout/activity_write_schedule_review.xml
  DaOnGil/presentation/src/main/res/values/strings.xml
Labels: UI/UX, 기능

#287 [#281] 파이어베이스 크래시틱스 적용
  DaOnGil/gradle/libs.versions.toml
  DaOnGil/presentation/build.gradle.kts
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/base/BaseViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/ext/FlowExt.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/vm/KeywordSearchViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/keyword/vm/SearchResultViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/fragment/SelectInterestFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/vm/InterestViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/login/vm/LoginViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/home/HomeViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/search/SearchListViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/main/vm/search/SearchMapViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/fragment/IceModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/fragment/PersonalInfoModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/vm/DeleteUserViewModel.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/myinfo/vm/MyInfoViewModel.kt
Labels: 기능

#288 [#286] 일정 후기 수정화면 접근성 개선
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/ModifyScheduleReviewActivity.kt
  DaOnGil/presentation/src/main/java/kr/tekit/lion/presentation/schedulereview/vm/ModifyScheduleReviewViewModel.kt
  DaOnGil/presentation/src/main/res/layout/activity_modify_schedule_review.xml
Labels: UI/UX, 기능

#293 #292 네트워크 상태 옵저빙 클래스 수정
  DaOnGil/app/src/main/java/kr/techit/lion/daongil_cleanarchitecture/App.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/bookmark/BookmarkActivity.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/concerntype/fragment/ConcernTypeFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/concerntype/fragment/ConcernTypeModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/emergency/fragment/EmergencyAreaDialog.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/emergency/fragment/PharmacyAreaDialog.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/emergency/vm/EmergencyInfoViewModel.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/home/DetailActivity.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/home/ReviewListActivity.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/home/WriteReviewActivity.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/keyword/KeywordSearchActivity.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/keyword/fragment/SearchResultFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/main/vm/myinfo/MyInfoMainViewModel.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/main/vm/search/SearchListViewModel.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/myinfo/fragment/IceModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/myinfo/fragment/MyInfoFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/myinfo/fragment/PersonalInfoModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/myinfo/vm/DeleteUserViewModel.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/myinfo/vm/MyInfoViewModel.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/myreview/fragment/MyReviewFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/myreview/fragment/MyReviewModifyFragment.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/myschedule/MyScheduleActivity.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/observer/NetworkConnectivityObserver.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/report/ReportActivity.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/schedule/PublicScheduleActivity.kt
  DaOnGil/presentation/src/main/java/kr/techit/lion/presentation/schedule/ScheduleDetailActivity.kt
Labels: 기능, 리팩토링
